name: Python

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash

jobs:
  Windows:    
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install python deps 
      run: pip install pytest numpy 
    - name: Build
      run: python setup.py build
    - name: Test
      run: python -m pytest --ignore docs --ignore dlib 

  Ubuntu:    
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: python setup.py build
    - name: Test
      run: python setup.py test 

  # we don't run python setup.py test on MacOS because there is some system
  # issue that prevents it from running at all.
  MacOS:    
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: python setup.py build

